import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import ts from 'typescript';
import 'fake-indexeddb/auto';
const url = source => 'data:text/javascript;base64,' + Buffer.from(source).toString('base64');
function compile(file) { return ts.transpileModule(readFileSync(file,'utf8'), { compilerOptions: { module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022 } }).outputText; }
const geometry = url(compile('lib/connections.ts'));
const entities = url(compile('lib/entities.ts').replace("'./connections'",JSON.stringify(geometry)));
const clipboard = url(compile('lib/clipboard-image.ts'));
const source = compile('lib/local-board.ts').replace("'./entities'",JSON.stringify(entities)).replace("'./clipboard-image'",JSON.stringify(clipboard));
const client = suffix => import(url(source + '\n// ' + suffix));
const req = request => new Promise((resolve,reject) => {request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});
const open = indexedDB.open('whiteboard-local',1);
open.onupgradeneeded=()=>open.result.createObjectStore('boards');
const legacy = await req(open);
const note={id:'a',x:0,y:0,text:'original',color:'#fff0a3',fontSize:18,bold:false};
const board={format:'whiteboard-entities',version:1,notes:[note],arrows:[]};
await req(legacy.transaction('boards','readwrite').objectStore('boards').put(board,'default')); legacy.close();
const a=await client('a'); assert.deepEqual(await a.loadLocalBoard(),board);
const image='data:image/png;base64,YQ==';
const changed={...board,notes:[{...note,text:'changed',image}]};
await a.saveLocalBoard(changed);
const b=await client('b'); assert.deepEqual(await b.loadLocalBoard(),changed);
await a.saveLocalBoard({...changed,notes:[{...changed.notes[0],text:'newest'}]});
await assert.rejects(()=>b.saveLocalBoard(board),/Another tab/);
assert.equal((await a.loadLocalBoard()).notes[0].text,'newest');
assert.equal((await a.loadPreviousBoard()).notes[0].text,'changed');
const db=await req(indexedDB.open('whiteboard-local',2));
assert.equal(await req(db.transaction('assets').objectStore('assets').count()),1);
const head=await req(db.transaction('boards').objectStore('boards').get('default'));
assert(head.board.notes[0].image.startsWith('asset:'));
await req(db.transaction('boards','readwrite').objectStore('boards').put({...head,board:{invalid:true}},'default'));
assert.equal((await a.loadLocalBoard()).notes[0].text,'changed'); assert.equal(a.recoveredBoard,true);
await a.saveLocalBoard(changed);
assert.equal((await a.loadLocalBoard()).notes[0].text,'changed');
// Repeated checkpoints stay bounded and do not duplicate images.
const realNow=Date.now; let now=realNow(); Date.now=()=>now;
for(let i=0;i<65;i++){now+=60001;await a.saveLocalBoard({...changed,notes:[{...changed.notes[0],text:String(i)}]});}
Date.now=realNow;
assert((await req(db.transaction('history').objectStore('history').count()))<=61);
assert.equal(await req(db.transaction('assets').objectStore('assets').count()),1);
console.log('Passed legacy migration, round-trip, image deduplication, stale-tab rejection, previous-save recovery, corrupt-head recovery, atomic head retention on conflict, and bounded history.');
db.close();

const entityAPI = await import(entities);
const frame = {...note,id:'frame',outline:true,borderStyle:'dashed',iconLabel:'Private network',width:520,height:360};
const frameBoard={...board,notes:[frame]};
assert(entityAPI.parseEntities(JSON.stringify(frameBoard)));
const duplicated=entityAPI.duplicateEntities(frameBoard,32);
assert.equal(duplicated.notes[0].borderStyle,'dashed');
assert.equal(duplicated.notes[0].iconLabel,'Private network');
assert.equal(duplicated.notes[0].width,520);
assert.equal(entityAPI.parseEntities(JSON.stringify({...board,notes:[{...frame,borderStyle:'invalid'}]})),null);
console.log('Passed outline serialization, label/style/dimensions copying, and invalid-style rejection.');

const { resizeBounds, resizeHandles } = await import(url(compile('lib/resize-outline.ts')));
const { anchor } = await import(geometry);
const originalSticky = { ...note, x: 40, y: 60, width: 240, height: 260, verticalAlign: 'middle' };
for (const handle of resizeHandles) {
  const bounds = resizeBounds(originalSticky, handle, 60, 40);
  if (handle.includes('w')) assert.equal(bounds.x + bounds.width, 280);
  else assert.equal(bounds.x, 40);
  if (handle.includes('n')) assert.equal(bounds.y + bounds.height, 320);
  else assert.equal(bounds.y, 60);
}
const resizedSticky = { ...originalSticky, ...resizeBounds(originalSticky, 'se', 60, 40) };
assert.deepEqual(anchor(resizedSticky, 'right'), { x: 340, y: 210 });
const stickyCopy = entityAPI.duplicateEntities({ ...board, notes: [resizedSticky] }, 32);
assert.equal(stickyCopy.notes[0].width, 300);
assert.equal(stickyCopy.notes[0].height, 300);
await a.saveLocalBoard({ ...board, notes: [resizedSticky] });
assert.deepEqual((await a.loadLocalBoard()).notes[0], resizedSticky);
console.log('Passed sticky resizing in eight directions, updated connection anchors, copied dimensions, and saved dimensions/alignment.');
const resizedIcon = { ...note, icon:'s3', iconLabel:'Archive', ...resizeBounds({x:40,y:60,width:120,height:128},'se',120,128) };
assert.deepEqual(anchor(resizedIcon,'right'),{x:280,y:188});
const copiedIcon = entityAPI.duplicateEntities({...board,notes:[resizedIcon]},32).notes[0];
assert.equal(copiedIcon.width,240);
assert.equal(copiedIcon.height,256);
assert.equal(copiedIcon.iconLabel,'Archive');
await a.saveLocalBoard({...board,notes:[resizedIcon]});
assert.deepEqual((await a.loadLocalBoard()).notes[0],resizedIcon);
console.log('Passed resized icon anchors, copied dimensions/label, and persistence.');
const {movementIds,moveEntities} = await import(url(compile('lib/move-entities.ts')));
const group=[{id:'n1',x:0,y:5},{id:'n2',x:80,y:90},{id:'outside',x:500,y:500}];
const linked=[{id:'link',from:{noteId:'n1'},to:{noteId:'n2'}}];
const moved=moveEntities(group,movementIds(['n1','n2','link'],linked),20,-10);
assert.deepEqual(moved,[{id:'n1',x:20,y:-5},{id:'n2',x:100,y:80},{id:'outside',x:500,y:500}]);
assert.equal(moved[1].x-moved[0].x,80);
assert.equal(moved[2],group[2]);
assert.deepEqual(moveEntities(group,movementIds(['link'],linked),20,-10),moved);
assert.deepEqual(group[0],{id:'n1',x:0,y:5});
console.log('Passed group translation, arrow endpoint movement, spacing, deduplication and unchanged unselected entities.');
const {touchesEntityBorder}=await import(url(compile('lib/selection.ts')));
const entity={x:100,y:100,width:200,height:200};
assert.equal(touchesEntityBorder({x:150,y:150,width:20,height:20},entity),false);
assert.equal(touchesEntityBorder({x:80,y:150,width:20,height:20},entity),true);
assert.equal(touchesEntityBorder({x:290,y:150,width:30,height:20},entity),true);
assert.equal(touchesEntityBorder({x:150,y:80,width:20,height:30},entity),true);
assert.equal(touchesEntityBorder({x:150,y:290,width:20,height:30},entity),true);
assert.equal(touchesEntityBorder({x:50,y:50,width:300,height:300},entity),true);
assert.equal(touchesEntityBorder({x:0,y:0,width:99,height:99},entity),false);
console.log('Passed marquee border contact, all four edges, enclosure, interior exclusion and disjoint selection.');
const {clickSelection}=await import(url(compile('lib/selection.ts')));
assert.deepEqual(clickSelection(['one'],'two',true),['one','two']);
assert.deepEqual(clickSelection(['one','two'],'two',true),['one','two']);
assert.deepEqual(clickSelection(['one'],'two',false),['two']);
assert.deepEqual(clickSelection(['one','two'],'one',false),['one','two']);
console.log('Passed additive click selection, no duplicates, replacement and group preservation.');
const {boardHistory,initialHistory}=await import(url(compile('lib/board-history.ts')));
let h=boardHistory(initialHistory(),{type:'reset',board:{notes:[{id:'a',x:0}],arrows:[{id:'edge'}]}});
h=boardHistory(h,{type:'notes',value:[{id:'a',x:5}],group:1});
h=boardHistory(h,{type:'notes',value:[{id:'a',x:25}],group:1});
assert.equal(h.past.length,1);
h=boardHistory(h,{type:'undo'});assert.equal(h.present.notes[0].x,0);
h=boardHistory(h,{type:'redo'});assert.equal(h.present.notes[0].x,25);
h=boardHistory(h,{type:'notes',value:[],group:2});
h=boardHistory(h,{type:'arrows',value:[],group:2});
h=boardHistory(h,{type:'undo'});assert.equal(h.present.notes.length,1);assert.equal(h.present.arrows.length,1);
h=boardHistory(h,{type:'notes',value:[{id:'new',x:7}],group:3});assert.equal(h.future.length,0);
for(let i=0;i<110;i++) h=boardHistory(h,{type:'notes',value:[{id:'a',x:i}],group:10+i});
assert.equal(h.past.length,100);
console.log('Passed grouped drag undo, redo, atomic node/arrow deletion undo, redo invalidation and bounded history.');
const labeledBoard={...board,notes:[note,{...note,id:'other',x:400}],arrows:[{id:'labeled',from:{noteId:note.id,side:'right'},to:{noteId:'other',side:'left'},label:'HTTP',bidirectional:true}]};
assert.deepEqual(entityAPI.parseEntities(JSON.stringify(labeledBoard)),labeledBoard);
const labelCopy=entityAPI.duplicateEntities(labeledBoard,32);
assert.equal(labelCopy.arrows[0].label,'HTTP');assert.equal(labelCopy.arrows[0].bidirectional,true);
assert.equal(entityAPI.parseEntities(JSON.stringify({...labeledBoard,arrows:[{...labeledBoard.arrows[0],bidirectional:'yes'}]})),null);
await a.saveLocalBoard(labeledBoard);
assert.deepEqual((await a.loadLocalBoard()).arrows,labeledBoard.arrows);
const {connectionMidpoint}=await import(geometry);
assert.deepEqual(connectionMidpoint({x:0,y:0},'right',{x:200,y:100},'left'),{x:100,y:50});
console.log('Passed arrow labels/two-way serialization, copy, persistence, validation and curve midpoint.');
