import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import ts from 'typescript';
import 'fake-indexeddb/auto';
const source = ts.transpileModule(readFileSync('lib/local-todos.ts', 'utf8'), { compilerOptions: { module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2022 } }).outputText;
const client = suffix => import('data:text/javascript;base64,' + Buffer.from(source + '\n// ' + suffix).toString('base64'));
const a = await client('a'), b = await client('b');
assert.deepEqual(await a.loadTodos(), []);
await Promise.all(['one', 'two'].map((id, i) => (i ? a : b).changeTodo({ type:'add', task:{ id, title:id, completed:false, createdAt:i } })));
assert.equal((await a.loadTodos()).length, 2);
await Promise.all([a.changeTodo({type:'update',id:'one',title:'Edited'}), b.changeTodo({type:'update',id:'one',completed:true})]);
assert.deepEqual((await b.loadTodos()).find(task => task.id === 'one'), { id:'one',title:'Edited',completed:true,createdAt:0 });
await assert.rejects(a.changeTodo({type:'update',id:'one',title:'  '}));
assert.equal((await a.loadTodos()).find(task => task.id === 'one').title, 'Edited');
await a.changeTodo({type:'delete',id:'one'});
await b.changeTodo({type:'update',id:'one',title:'Stale edit'});
assert.equal((await a.loadTodos()).length, 1);
console.log('To-do persistence passed: reload, concurrent changes, validation, deletion, stale edits.');
assert.equal(a.taskStatus({completed:false}), 'todo');
assert.equal(a.taskStatus({completed:true}), 'done');
await a.changeTodo({type:'update',id:'two',status:'in-progress'});
assert.equal(a.taskStatus((await b.loadTodos())[0]), 'in-progress');
assert.equal((await b.loadTodos())[0].completed, false);
await Promise.all([a.changeTodo({type:'update',id:'two',status:'done'}), b.changeTodo({type:'update',id:'two',title:'Kept while moving'})]);
assert.deepEqual((await b.loadTodos())[0], {id:'two',title:'Kept while moving',completed:true,createdAt:1,status:'done'});
await a.changeTodo({type:'update',id:'two',status:'todo'});
assert.equal((await a.loadTodos())[0].completed, false);
await assert.rejects(a.changeTodo({type:'update',id:'two',status:'invalid'}));
assert.equal(a.taskStatus((await a.loadTodos())[0]), 'todo');
console.log('Task board passed: legacy status mapping, persisted transitions, concurrent edit/move, reopening, invalid status rejection.');
await a.changeTodo({type:'update',id:'two',status:'blocked',description:'Waiting for review',dueDate:'2026-09-15'});
let details = (await b.loadTodos())[0];
assert.equal(details.description, 'Waiting for review');
assert.equal(details.status, 'blocked');
assert.equal(details.completed, false);
assert.equal(a.dueInfo(details, new Date(2026,8,12,23,59)).label, '3 days left');
assert.equal(a.dueInfo(details, new Date(2026,8,15)).label, 'Due today');
assert.equal(a.dueInfo(details, new Date(2026,8,16)).label, '1 day overdue');
assert.equal(a.dueInfo({...details,status:'done'}, new Date(2026,8,16)).tone, 'complete');
assert.equal(a.dueInfo({...details,dueDate:'2026-03-09'}, new Date(2026,2,8,23,59)).days, 1);
assert.equal(a.validDueDate('2026-02-30'), false);
assert.equal(a.validDueDate('2028-02-29'), true);
await assert.rejects(a.changeTodo({type:'update',id:'two',dueDate:'2026-02-30'}));
await a.changeTodo({type:'update',id:'two',title:'Properties preserved'});
assert.equal((await a.loadTodos())[0].description, 'Waiting for review');
await a.changeTodo({type:'update',id:'two',description:'',dueDate:''});
assert.equal(a.dueInfo((await a.loadTodos())[0]), null);
console.log('Task properties passed: blocked, descriptions, dates, clearing fields, overdue/today/remaining/completed badges, DST calendar days.');
await a.changeTodo({type:'update',id:'two',priority:'high',tags:['routing','my-project'],checklist:[{id:'step1',title:'Write tests',completed:false},{id:'step2',title:'Review',completed:true}],dueDate:'2026-09-12'});
let rich = (await b.loadTodos())[0];
assert.equal(rich.priority, 'high');
assert.deepEqual(rich.tags, ['routing','my-project']);
assert.equal(rich.checklist.filter(item => item.completed).length, 1);
assert.equal(a.isTodayTask(rich,new Date(2026,8,12)),true);
assert.equal(a.isTodayTask(rich,new Date(2026,8,13)),true);
assert.equal(a.isTodayTask(rich,new Date(2026,8,11)),false);
assert.equal(a.isTodayTask({...rich,status:'done'},new Date(2026,8,12)),false);
assert.equal(a.isTodayTask({...rich,dueDate:''},new Date(2026,8,12)),false);
await a.changeTodo({type:'update',id:'two',status:'in-progress'});
assert.deepEqual((await b.loadTodos())[0].checklist,rich.checklist);
await assert.rejects(a.changeTodo({type:'update',id:'two',priority:'urgent'}));
await assert.rejects(a.changeTodo({type:'update',id:'two',tags:['bug','bug']}));
await assert.rejects(a.changeTodo({type:'update',id:'two',checklist:[{id:'x',title:'',completed:false}]}));
await a.changeTodo({type:'update',id:'two',tags:[],checklist:[]});
assert.deepEqual((await b.loadTodos())[0].tags,[]);
assert.deepEqual((await b.loadTodos())[0].checklist,[]);
console.log('Priority, tags, checklist round-trip/validation and Today filtering passed.');
