/* Official SVG assets are bundled locally; no optimization server is needed. */
/* oxlint-disable next/no-img-element */
import { Square, Diamond, Circle, FileText, Workflow, Merge, Split, Timer, CircleCheck, CircleX, Router, Wifi, Cable, Cloud, BrickWall, ShieldCheck, LockKeyhole, KeyRound, Fingerprint, BadgeCheck, Table2, HardDrive, Folder, Search, ChartColumn, Waves, Users, Building2, Monitor, Laptop, Smartphone, Radio, Mail, Bell, MessagesSquare, CreditCard, Bot, Code2, Terminal, Package, FlaskConical, Rocket, Archive, Server, FunctionSquare, Database, ListOrdered, Globe, Network, Zap, Container, PanelsTopLeft, User, GitFork } from 'lucide-react';
import { iconCatalog } from '@/lib/icon-catalog';
const symbols = { Archive, Container, Network, Server, Zap, ListOrdered, GitFork, Globe, Square, Diamond, Circle, FileText, Workflow, Merge, Split, Timer, CircleCheck, CircleX, Router, Wifi, Cable, Cloud, BrickWall, ShieldCheck, LockKeyhole, KeyRound, Fingerprint, BadgeCheck, Table2, HardDrive, Folder, Search, ChartColumn, Waves, Users, Building2, Monitor, Laptop, Smartphone, Radio, Mail, Bell, MessagesSquare, CreditCard, Bot, Code2, Terminal, Package, FlaskConical, Rocket,  bucket: Archive, server: Server, function: FunctionSquare, database: Database, queue: ListOrdered, globe: Globe, network: Network, cache: Zap, container: Container, browser: PanelsTopLeft, user: User, git: GitFork };
export function DiagramIcon({ id, label, scale }: { id: string; label?: string; scale?: number }) {
  const item = iconCatalog.find(icon => icon.id === id);
  if (!item) return null;
  const Icon = symbols[item.symbol];
  const official = id.startsWith('dev-') || id.startsWith('aws-') || ['s3', 'ec2', 'lambda', 'rds', 'dynamodb', 'sqs', 'cloudfront', 'api-gateway', 'github', 'cache'].includes(id);
  return <span className="diagram-icon" style={scale === undefined ? undefined : { gap: 10 * scale }}><span className={official ? "diagram-icon-symbol official-logo" : "diagram-icon-symbol"} style={{ background: official ? "transparent" : item.color, ...(scale === undefined ? {} : { width: 66 * scale, height: 66 * scale, flexShrink: 0 }) }}>{official ? <img src={"/icons/" + id + ".svg"} alt="" draggable={false} /> : <Icon size={36 * (scale ?? 1)} strokeWidth={1.7} />}</span><span className="diagram-icon-label" style={scale === undefined ? undefined : { fontSize: 14 * scale, maxHeight: 44 * scale }}>{label ?? item.label}</span></span>;
}
