export const engineeringIcons = [
  {id:'container-image',label:'Container image / OCI image',symbol:'Package'},
  {id:'image-registry',label:'Container image registry',symbol:'Archive'},
  {id:'dockerfile',label:'Dockerfile / Container build',symbol:'FileText'},
  {id:'k8s-pod',label:'K8s Pod',symbol:'Container'},
  {id:'k8s-cluster',label:'K8s Cluster',symbol:'Network'},
  {id:'k8s-node',label:'K8s Worker node',symbol:'Server'},
  {id:'k8s-deployment',label:'K8s Deployment',symbol:'Rocket'},
  {id:'k8s-service',label:'K8s Service',symbol:'Router'},
  {id:'k8s-ingress',label:'K8s Ingress',symbol:'Globe'},
  {id:'k8s-namespace',label:'K8s Namespace',symbol:'Folder'},
  {id:'k8s-configmap',label:'K8s ConfigMap',symbol:'FileText'},
  {id:'k8s-secret',label:'K8s Secret',symbol:'KeyRound'},
  {id:'k8s-volume',label:'K8s Persistent volume / PVC',symbol:'HardDrive'},
  {id:'k8s-job',label:'K8s Job / CronJob',symbol:'Timer'},
  {id:'ci-pipeline',label:'CI/CD Pipeline',symbol:'Workflow'},
  {id:'build-runner',label:'Build runner / Agent',symbol:'Terminal'},
  {id:'unit-tests',label:'Unit / Integration tests',symbol:'FlaskConical'},
  {id:'artifact-store',label:'Artifact repository',symbol:'Archive'},
  {id:'microservice',label:'Microservice / API',symbol:'Code2'},
  {id:'background-worker',label:'Background worker',symbol:'Bot'},
  {id:'webhook',label:'Webhook / Event handler',symbol:'Zap'},
  {id:'metrics',label:'Metrics / Monitoring',symbol:'ChartColumn'},
  {id:'logs',label:'Logs / Log collector',symbol:'ListOrdered'},
  {id:'tracing',label:'Distributed tracing',symbol:'GitFork'},
] as const;
